// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pj_ds_KomirkaApp_API;

#nullable disable

namespace pj_ds_KomirkaApp_API.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20250617201519_upd-db")]
    partial class upddb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("pj_ds_KomirkaApp_API.Models.Cell", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DrawerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("UniqueNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.Property<int>("WightCapacity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DrawerId");

                    b.ToTable("Cells");
                });

            modelBuilder.Entity("pj_ds_KomirkaApp_API.Models.Drawer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("ClosesTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("OpensTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("Drawers");
                });

            modelBuilder.Entity("pj_ds_KomirkaApp_API.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("pj_ds_KomirkaApp_API.Models.UserCellAccess", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CellId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "CellId");

                    b.HasIndex("CellId");

                    b.ToTable("UserCellAccesses");
                });

            modelBuilder.Entity("pj_ds_KomirkaApp_API.Models.UserInfo", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("UsersInfo");
                });

            modelBuilder.Entity("pj_ds_KomirkaApp_API.Models.Cell", b =>
                {
                    b.HasOne("pj_ds_KomirkaApp_API.Models.Drawer", "Drawer")
                        .WithMany("Cells")
                        .HasForeignKey("DrawerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drawer");
                });

            modelBuilder.Entity("pj_ds_KomirkaApp_API.Models.UserCellAccess", b =>
                {
                    b.HasOne("pj_ds_KomirkaApp_API.Models.Cell", "Cell")
                        .WithMany("UserAccesses")
                        .HasForeignKey("CellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pj_ds_KomirkaApp_API.Models.User", "User")
                        .WithMany("CellAccesses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cell");

                    b.Navigation("User");
                });

            modelBuilder.Entity("pj_ds_KomirkaApp_API.Models.UserInfo", b =>
                {
                    b.HasOne("pj_ds_KomirkaApp_API.Models.User", "User")
                        .WithOne("UserInfo")
                        .HasForeignKey("pj_ds_KomirkaApp_API.Models.UserInfo", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("pj_ds_KomirkaApp_API.Models.Cell", b =>
                {
                    b.Navigation("UserAccesses");
                });

            modelBuilder.Entity("pj_ds_KomirkaApp_API.Models.Drawer", b =>
                {
                    b.Navigation("Cells");
                });

            modelBuilder.Entity("pj_ds_KomirkaApp_API.Models.User", b =>
                {
                    b.Navigation("CellAccesses");

                    b.Navigation("UserInfo")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
